# Generated by Django 3.2.13 on 2022-09-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociateRequest',
        ),
    ]
