# Generated by Django 3.2.13 on 2022-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
