# Generated by Django 3.2.13 on 2022-06-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_name',
            new_name='name',
        ),
    ]
