# Generated by Django 3.2.13 on 2022-06-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_venue_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gigs.venue'),
        ),
    ]
