# Generated by Django 3.2.13 on 2022-07-22 20:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0007_auto_20220619_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='personnel',
            field=models.ManyToManyField(related_name='gig_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 22, 16, 44, 32, 288995)),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 22, 16, 44, 32, 288969)),
        ),
    ]
