# Generated by Django 3.2.13 on 2022-07-24 20:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0008_auto_20220722_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='acccepts',
            field=models.ManyToManyField(related_name='gig_accepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 24, 16, 35, 5, 835316)),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 24, 16, 35, 5, 835296)),
        ),
    ]
