# Generated by Django 3.2.13 on 2022-08-17 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_auto_20220728_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='call_time',
            field=models.TimeField(blank=True, default=120000, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 17, 11, 9, 24, 824296)),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 17, 11, 9, 24, 824258)),
        ),
    ]
