# Generated by Django 3.2.13 on 2022-08-18 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_auto_20220817_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='call_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 18, 12, 0), null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 18, 10, 8, 26, 451197)),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 18, 12, 0)),
        ),
    ]
