# Generated by Django 3.2.13 on 2022-08-18 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_auto_20220818_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='call_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 18, 19, 0)),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 18, 16, 0)),
        ),
    ]
