# Generated by Django 3.2.13 on 2022-08-18 14:22

from django.db import migrations, models
import gigs.models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_auto_20220818_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, default=gigs.models.default_event_date, null=True),
        ),
    ]
