# Generated by Django 3.2.13 on 2022-08-18 14:28

from django.db import migrations, models
import gigs.models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_alter_gig_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, default=gigs.models.default_event_date, help_text='Write date/time in this format: yyyy-mm-dd hh-mm-ss', null=True),
        ),
    ]
