# Generated by Django 3.2.13 on 2022-08-31 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0015_alter_gig_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='end_time',
            field=models.TimeField(default='07:00 PM'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 30, 21, 12, 13, 591162), help_text='Write date/time in this format: yyyy-mm-dd hh-mm-ss', null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(default='04:00 PM'),
        ),
    ]
