# Generated by Django 3.2.13 on 2022-08-31 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0016_auto_20220830_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 31, 11, 29, 43, 954502), null=True),
        ),
    ]
