# Generated by Django 3.2.13 on 2022-08-31 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0017_alter_gig_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 31, 0, 0, 0, 883549), help_text='Write date/time in this format: yyyy-mm-dd hh-mm-ss', null=True),
        ),
    ]
