# Generated by Django 3.2.13 on 2022-09-14 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0019_alter_gig_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 0, 0, 0, 911042), help_text='Write date/time in this format: yyyy-mm-dd hh-mm-ss', null=True),
        ),
    ]
