# Generated by Django 3.2.13 on 2022-10-04 16:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0021_auto_20221002_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='acccepts',
            field=models.ManyToManyField(blank=True, related_name='gig_accepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='declines',
            field=models.ManyToManyField(blank=True, related_name='gig_declines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 4, 0, 0, 0, 874611), help_text='Write date/time in this format: yyyy-mm-dd hh-mm-ss', null=True),
        ),
    ]
